name: Publish Docker # Имя инструкции

on: # Инструкция будет запускаться при push в ветку main
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # Мы берем мастер ветку
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4 # Мы используем готовый экшн для сборки докер образа
        with: # Ниже указаны параметры для экшна
          registry: ghcr.io
          name: popenkov/docker-ci-cd/docker-ci-cd
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'
